-- カラム追加
ALTER TABLE livers
ADD COLUMN IF NOT EXISTS group_id INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS debut_date DATE DEFAULT NULL,
Add COLUMN IF NOT EXISTS platform_id INT DEFAULT NULL;


-- 外部キー追加
ALTER TABLE livers
ADD CONSTRAINT fk_group
FOREIGN KEY (group_id) REFERENCES groups(id)
ON DELETE SET NULL;