CREATE TABLE articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    liver_id INT NOT NULL,
    related_liver_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    content TEXT NOT NULL,
    tags JSON,
    likes INT DEFAULT 0,
    thumbnail_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (liver_id) REFERENCES livers(id) ON DELETE CASCADE
);

ALTER TABLE articles
ADD COLUMN IF NOT EXISTS body TEXT NOT NULL;

